config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'posts#index'

  resources :posts
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
    :registerable,
    :recoverable,
    :rememberable,
    :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  PER_PAGE = 10

  def new
    @post = Post.new
  end

  def create
    @post = User.first.posts.build(create_params)

    if @post.save
      redirect_to @post, notice: 'Post created successfully'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @posts = Post.includes(:user).order(created_at: :desc).limit(PER_PAGE)
  end

  def show
    @post = Post.includes(:user).find(params[:id])
  end

  def edit
    @post = Post.includes(:user).find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(update_params)
      redirect_to @post, notice: 'Post updated successfully'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.destroy
      redirect_to root_url, notice: 'Post deleted successfully'
    else
      redirect_to @post, alert: 'Post could not be deleted'
    end
  end

  private

  def create_params
    params.require(:post).permit(:title, :body)
  end

  def update_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  PER_PAGE = 10

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.includes(:user)
      .order(created_at: :desc)
      .limit(PER_PAGE)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PorcupinePost</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="container">
    <div class="max-w-md mx-auto pb-8">
      <% if flash.notice %>
        <p><%= flash.notice %></p>
      <% end %>
      <% if flash.alert %>
        <p><%= flash.alert %></p>
      <% end %>

      <h1 class="font-serif text-xl my-8 text-center">
        <%= link_to 'Welcome to the Porcupine Post', root_path %>
      </h1>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_card.html.erb
<div class="post-card mb-5 p-2 shadow border">
  <h2 class="text-lg mb-2">
    <%= link_to post.title, post, class: 'text-blue-400 hover:text-blue-300' %>
  </h2>
  <footer class="flex">
    <div class="-mt-2 text-gray-600 flex-grow text-xs">
      <span class="font-serif italic">by</span>
      <%= link_to post.user.name, post.user, class: 'text-blue-400 hover:text-blue-300 uppercase' %>
    </div>
    <div class="text-right text-xs text-muted text-gray-400">
      <%= time_ago_in_words(post.created_at) %> ago
    </div>
  </footer>
</div>

app/views/posts/_detail.html.erb
<div class="post-detail">
  <h1 class="text-xl mb-3">
    <%= @post.title %>
  </h1>
  <div class="-mt-3 mb-3">
    <span class="font-serif italic">by</span>
    <span class="text-blue-400 hover:text-blue-300"><%= link_to @post.user.name, user_path(@post.user) %></span>
  </div>

  <div class="leading-relaxed">
    <%= @post.body %>
  </div>

  <ul class="flex items-center mt-5 border-t-2 p-5">
    <li class="mr-5 flex-grow">
      <%= link_to "Edit", edit_post_path(@post), class: 'p-3 bg-blue-400 text-white shadow rounded leading-none text-center' %>
    </li>
    <li>
      <%= button_to "Delete", @post, method: :delete, class: 'p-2 bg-red-400 text-white shadow rounded leading-none text-center' %>
    </li>
  </ul>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_with model: @post, local: true do |f| %>
  <% if @post.errors.present? %>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <%= f.label :title, 'Title' %>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :body, 'Body' %>
    <%= f.text_area :body, rows: 5 %>
  </div>
  <div class="form-controls">
    <%= f.submit "Save" %>
  </div>
<% end %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <%= render 'posts/card', post: post %>
<% end %>

<%= link_to 'New Post', new_post_path, class: 'px-3 py-4 bg-blue-400 text-white shadow rounded block w-1/2 leading-none text-center mx-auto' %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= form_with model: @post, local: true do |f| %>
  <% if @post.errors.present? %>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <%= f.label :title, 'Title' %>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :body, 'Body' %>
    <%= f.text_area :body, rows: 5 %>
  </div>
  <div class="form-controls">
    <%= f.submit "Create" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<%= render 'posts/detail', post: @post %>

app/views/users/show.html.erb
<h1 class="text-lg mb-8">Posts by <%= @user.name %></h1>
<% @posts.each do |post| %>
  <%= render 'posts/card', post: post %>
<% end %>